"""
Pydantic models for request/response validation and data structures.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime


class ReviewCategory(str, Enum):
    """Semantic categories for code review comments."""
    FUNCTIONAL = "functional"
    REFACTORING = "refactoring"
    DOCUMENTATION = "documentation"
    STYLE = "style"
    SECURITY = "security"
    PERFORMANCE = "performance"
    DISCUSSION = "discussion"


class Severity(str, Enum):
    """Severity levels for review comments."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class CodeChange(BaseModel):
    """Represents a single file change in a PR."""
    filename: str = Field(..., description="Path to the changed file")
    status: str = Field(..., description="Git status: added, modified, removed")
    additions: int = Field(default=0)
    deletions: int = Field(default=0)
    patch: Optional[str] = Field(default=None, description="Unified diff patch")
    previous_content: Optional[str] = Field(default=None)
    new_content: Optional[str] = Field(default=None)


class ReviewComment(BaseModel):
    """A single review comment generated by the system."""
    id: str = Field(..., description="Unique comment ID")
    category: ReviewCategory
    severity: Severity
    file_path: str
    line_number: Optional[int] = None
    message: str = Field(..., description="Review comment text")
    suggestion: Optional[str] = Field(default=None, description="Suggested fix")
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    retrieved_context: Optional[List[str]] = Field(default=None)
    model_used: str = Field(default="codellama-7b")
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PullRequestPayload(BaseModel):
    """GitHub PR webhook payload."""
    pr_number: int
    repository: str
    owner: str
    title: str
    description: Optional[str] = None
    branch: str
    base_branch: str
    author: str
    changes: List[CodeChange]
    installation_id: Optional[int] = None


class ReviewRequest(BaseModel):
    """Request to generate a code review."""
    pr_payload: PullRequestPayload
    review_style: Optional[str] = Field(default="balanced", description="strict|balanced|lenient")
    focus_areas: Optional[List[ReviewCategory]] = Field(default=None)


class ReviewResponse(BaseModel):
    """Response containing generated review."""
    review_id: str
    pr_number: int
    repository: str
    summary: str
    comments: List[ReviewComment]
    overall_score: float = Field(ge=0.0, le=100.0)
    processing_time_ms: int
    model_version: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class HistoricalReview(BaseModel):
    """A historical review entry for RAG retrieval."""
    id: str
    repository: str
    category: ReviewCategory
    code_snippet: str
    review_comment: str
    severity: Severity
    embedding: Optional[List[float]] = None
    created_at: datetime


class HealthCheck(BaseModel):
    """Health check response."""
    status: str
    version: str = "1.0.0"
    model_loaded: bool
    vector_store_ready: bool
    uptime_seconds: int
